<div class="share-wrapper">
    <span class="share-span"><?= __('Share this') ?></span>
    <div class="share-links-wrapper">
        <a class="facebook-like" href="#"><i class="fab fa-facebook-square"></i><span class="share-link"><?= __('Like') ?></span></a>
        <a class="facebook-share" href="#"><span class="share-link"><?= __('Share') ?></span></a>
        <span class="share-label facebook"><?= __('235K') ?></span>
    </div>
    <div class="share-links-wrapper">
        <a class="share-twitter" href="#"><i class="fab fa-twitter"></i><span class="share-link"><?= __('Tweet') ?></span></a>
        <span class="share-label twitter"><?= __('93') ?></span>
    </div>
    <div class="share-links-wrapper">
        <a class="share-pin" href="#">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/pin_it.png')); ?>">
        </a>
        <span class="share-label pinterest"><?= __('65K+') ?></span>
    </div>
</div>
